[build]
  base = "frontend/"
  command = "next build && next export && cd ../netlify/functions && npm install && cd ../../frontend"
  publish = "out"
[functions]
  directory = "../netlify/functions/"
